// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmxrcfwduhmpopjaceno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdteHJjZndkdWhtcG9wamFjZW5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMTE2NDgsImV4cCI6MjA2MjY4NzY0OH0.7dHEDlnsrQyBjg-jll321x7aqnBaHQxPU9FYsYof10g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);